### ISSUE TITLE
There is no exception when starting multiple processes

### ISSUE THREAD

**Issue by rodion-k** [supervisorphp/supervisor#20]
If start single process which fail, then exception is thrown:
```php
$supervisor->startProcess('queue-seller:seller-1');
```
`Exception 'fXmlRpc\Exception\FaultException' with message 'NO_FILE: can't find command 'test''`

But if start a group of processes:
```php
$supervisor->startProcess('queue-seller:*');
```
the output is:
```php
array(
  0 => array(
    'status' => 20,
    'group' => 'queue-seller',
    'name' => 'seller-8',
    'description' => 'NO_FILE: can\'t find command \'test\''
  ),
  1 => array(
    'status' => 20,
    'group' => 'queue-seller',
    'name' => 'seller-9',
    'description' => 'NO_FILE: can\'t find command \'test\''
  ),
)
```

How to correctly determine that an error occurred?

**Comment by sagikazarmark** [comment]
When you start multiple processes some might fail, some might not. In that case a single fault is not a valid answer, since the request did not end up in a fault.

I would take a look at that status field...unfortunately I'm not using supervisor for some time, so I can't help with that.

Alternatively you could get process info after calling the methods and see process states there.

Hope this helps!
